# Form implementation generated from reading ui file 'DailyAimChoice.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DailyAimChoiceWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(350, 160)
        MainWindow.setWindowTitle("Ежедневная цель")
        MainWindow.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        buttonStyle = open("styles/commonButtonStyle.css").read()
        editStyle = open("styles/Entry.css").read()
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.bg_label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bg_label.setStyleSheet("background-image: url(resources/choice_bg.jpg);")
        self.bg_label.setText("")
        self.bg_label.setObjectName("bg_label")
        self.amountEntry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.amountEntry.setGeometry(QtCore.QRect(10, 70, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.amountEntry.setFont(font)
        self.amountEntry.setStyleSheet(editStyle)
        self.amountEntry.setObjectName("amountEntry")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.acceptButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.acceptButton.setGeometry(QtCore.QRect(230, 70, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.acceptButton.setFont(font)
        self.acceptButton.setStyleSheet(buttonStyle)
        self.acceptButton.setObjectName("acceptButton")
        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 26))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите целевое количество\n"
"слов на этот день"))
        self.acceptButton.setText(_translate("MainWindow", "ОК"))
        self.amountEntry.setText(_translate("MainWindow", "100"))
