# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 600)
        MainWindow.setWindowTitle("Тренажёр ударений")
        MainWindow.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        buttonStyle = open("styles/commonButtonStyle.css").read()
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.bg_label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bg_label.setStyleSheet("background-image: url(resources/background.jpg);")
        self.bg_label.setText("")
        self.bg_label.setObjectName("bg_label")
        self.mainLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(130, 20, 521, 151))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.mainLabel.setFont(font)
        self.mainLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.mainLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.mainLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mainLabel.setAutoFillBackground(False)
        self.mainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mainLabel.setObjectName("label")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(300, 200, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet(buttonStyle)
        self.startButton.setObjectName("pushButton")
        self.editTasksButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editTasksButton.setGeometry(QtCore.QRect(300, 280, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.editTasksButton.setFont(font)
        self.editTasksButton.setStyleSheet(buttonStyle)
        self.editTasksButton.setObjectName("editTasksButton")
        self.statisticsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.statisticsButton.setGeometry(QtCore.QRect(300, 360, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.statisticsButton.setFont(font)
        self.statisticsButton.setStyleSheet(buttonStyle)
        self.statisticsButton.setObjectName("pushButton_3")
        self.generatorButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generatorButton.setGeometry(QtCore.QRect(300, 440, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.generatorButton.setFont(font)
        self.generatorButton.setStyleSheet(buttonStyle)
        self.generatorButton.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainLabel.setText(_translate("MainWindow", "Тренажёр ударений"))
        self.startButton.setText(_translate("MainWindow", "Начать"))
        self.editTasksButton.setText(_translate("MainWindow", "Редактировать задания"))
        self.statisticsButton.setText(_translate("MainWindow", "Статистика"))
        self.generatorButton.setText(_translate("MainWindow", "Сгенерировать задания"))
