# Form implementation generated from reading ui file 'Statistics.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.weeklyGraph = PlotWidget(parent=self.centralwidget)
        self.weeklyGraph.setGeometry(QtCore.QRect(10, 170, 440, 250))
        self.weeklyGraph.setObjectName("weeklyGraph")
        self.todayStatLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.todayStatLabel.setGeometry(QtCore.QRect(180, 20, 460, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.todayStatLabel.setFont(font)
        self.todayStatLabel.setText("")
        self.todayStatLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.todayStatLabel.setObjectName("todayStatLabel")
        self.weekStatLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.weekStatLabel.setGeometry(QtCore.QRect(20, 80, 430, 90))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.weekStatLabel.setFont(font)
        self.weekStatLabel.setObjectName("weekStatLabel")
        self.mistakeCountLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.mistakeCountLabel.setGeometry(QtCore.QRect(480, 80, 290, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.mistakeCountLabel.setFont(font)
        self.mistakeCountLabel.setObjectName("mistakeCountLabel")
        self.mistakesTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.mistakesTable.setGeometry(QtCore.QRect(480, 160, 290, 341))
        self.mistakesTable.setObjectName("mistakesTable")
        self.mistakesTable.setColumnCount(0)
        self.mistakesTable.setRowCount(0)
        self.clearHistoryButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearHistoryButton.setGeometry(QtCore.QRect(480, 507, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.clearHistoryButton.setFont(font)
        self.clearHistoryButton.setObjectName("clearHistoryButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.weekStatLabel.setText(_translate("MainWindow", "Количество решённый заданий\n"
"за неделю"))
        self.mistakeCountLabel.setText(_translate("MainWindow", "Слова в которых были\n"
"допущены ошибки"))
        self.clearHistoryButton.setText(_translate("MainWindow", "Очистить историю"))
from plotwidget import PlotWidget
